### ISSUE TITLE
CLANG: Compilation fails with variable length array

### ISSUE THREAD

**Issue by ThomasVogelpohl** [pwuertz/qmlplotting#1]
Hi Peter, 
compilation with Clang of paintPolygon fails, because you are using a variable length array called points
in the paintPolygon() function:

```
static void paintPolygon(QImage& img, int segments, bool border) {
    int size = img.width();
    QPainter p(&img);
    if (!border) p.setPen(Qt::NoPen);
    p.setBrush(QColor(Qt::white));

    if (segments) {
        QPointF points[segments];
```

As far as I understand, Clang C++ 11 supports just POD type vaiable length arrays.
The recommendation is to use a Vector in case variable lengh is needed.

Could you please tell me what compiler you are using ?
I am using the latest Mac Yosemite toolchain.

Thanks,
Thomas

**Comment by pwuertz** [comment]
Hi! I tested this code using GCC on Ubuntu and Windows so far, trying to use C++11 features whenever I saw an opportunity. In the latest commit (e0c438e435a8e7673f54de3c94a8f74ffef2ba10) I changed this part so it uses a std::vector instead of a variable length array now. Using variable length arrays for POD types only seems reasonable. 

I'd be happy to see it working on OSX as well (or clang in general). Is this fix enough for a successful build? If not, please feel free to post other compatibility issues here.

**Comment by ThomasVogelpohl** [comment]
Hi Peter,

compilation works fine now. Thanks for the fast fix !

BR,
Thomas
